<?php

namespace App\Http\Controllers\Web;

use App\Domain\Seo\Services\SitemapBuilder;
use App\Http\Controllers\Controller;
use App\Models\Setting;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;

/**
 * Sitemaps are generated by a scheduled command and served as static files.
 * If a build has never run, the index is generated on the fly rather than
 * returning a 404 to a crawler that just found the robots.txt line.
 */
class SitemapController extends Controller
{
    public function index(SitemapBuilder $builder): Response
    {
        $path = SitemapBuilder::DIR.'/index.xml';
        $disk = Storage::disk(SitemapBuilder::DISK);

        if (! $disk->exists($path)) {
            $builder->build();
        }

        return response($disk->get($path), 200, ['Content-Type' => 'application/xml']);
    }

    public function section(SitemapBuilder $builder, string $name): Response
    {
        $disk = Storage::disk(SitemapBuilder::DISK);
        $path = SitemapBuilder::DIR.'/'.basename($name).'.xml';

        abort_unless($disk->exists($path), 404);

        return response($disk->get($path), 200, ['Content-Type' => 'application/xml']);
    }

    /**
     * robots.txt is generated so it can never drift from the routes.
     *
     * Everything behind a login is disallowed — not for security (that is what
     * the auth middleware is for) but so crawl budget goes to pages that can
     * actually rank.
     */
    public function robots(): Response
    {
        $lines = ['User-agent: *'];

        if (Setting::get('maintenance_mode') || ! app()->environment('production')) {
            // A staging site indexed is worse than a staging site invisible.
            $lines[] = 'Disallow: /';
        } else {
            foreach (['/admin', '/dealer', '/account', '/ajax', '/api', '/login', '/documents', '/compare/'] as $path) {
                $lines[] = 'Disallow: '.$path;
            }

            $lines[] = 'Disallow: /*?utm_';
            $lines[] = 'Allow: /';
        }

        $lines[] = '';
        $lines[] = 'Sitemap: '.route('sitemap.index');

        return response(implode("\n", $lines)."\n", 200, ['Content-Type' => 'text/plain']);
    }
}
